# cmake/EmbedCaBundle.cmake - embeds the Mozilla CA bundle as a C++ source.
#
# Invoked as:
#   cmake -DCACERT_PEM=<path/to/cacert.pem> -DOUTPUT=<path/to/cacert_bundle.cc>
#         -P cmake/EmbedCaBundle.cmake
#
# Emits xe::app::kEmbeddedCaBundle (+Size). When the bundle is absent
# (setup skipped, or run without --ca-bundle) an empty bundle is emitted instead
# so the build never breaks -- TLS verification then fails closed at runtime.

if(DEFINED CACERT_PEM AND EXISTS "${CACERT_PEM}")
  file(READ "${CACERT_PEM}" _pem_raw)
  file(SIZE "${CACERT_PEM}" _pem_len)
  string(REPLACE "\\" "\\\\" _pem_esc "${_pem_raw}")
  string(REPLACE "\"" "\\\"" _pem_esc "${_pem_esc}")
  string(REPLACE "\n" "\\n\"\n\"" _pem_esc "${_pem_esc}")
  set(_pem_body "\"${_pem_esc}\"")
else()
  set(_pem_body "\"\"")
  set(_pem_len 0)
endif()

# string(CONCAT), not set(): set() with several arguments builds a
# semicolon-separated list, which would emit ';' where the newlines belong.
string(CONCAT _bundle
  "// Generated by cmake/EmbedCaBundle.cmake - do not edit.\n"
  "// Mozilla CA bundle (https://curl.se/ca/cacert.pem), embedded so hermetic\n"
  "// TLS (wolfSSL) needs no sidecar file. Empty when the bundle was absent\n"
  "// at build time.\n"
  "namespace xe {\n"
  "namespace app {\n"
  "\n"
  "extern const char kEmbeddedCaBundle[] =\n${_pem_body};\n"
  "extern const unsigned long kEmbeddedCaBundleSize = ${_pem_len};\n"
  "\n"
  "}  // namespace app\n"
  "}  // namespace xe\n")

# Write only when the content actually differs. This script runs at configure
# time (and `xb build` configures every run), and an unconditional file(WRITE)
# would bump the timestamp each time, making the generator recompile this
# translation unit on every build even though the bundle never changed.
set(_existing "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _existing)
endif()
if(NOT _existing STREQUAL _bundle)
  file(WRITE "${OUTPUT}" "${_bundle}")
elseif(DEFINED CACERT_PEM AND EXISTS "${CACERT_PEM}"
       AND "${CACERT_PEM}" IS_NEWER_THAN "${OUTPUT}")
  # Content matches but the bundle was re-fetched (e.g. `xb ca-bundle` pulled
  # an unchanged file). Refresh the timestamp so the output is not left
  # permanently older than its dependency, which would make the build system
  # recompile this translation unit on every single build.
  file(TOUCH "${OUTPUT}")
endif()
